### ISSUE TITLE
Calender with iCal

### ISSUE THREAD

**Issue by stirlingzero** [entropia/landing-page#17]
The embedded calendar could be fitted with an iCal-Import, where you can Import Nextcloud Calender's, to show it's entries.

**Comment by pascalwittler** [comment]
I guess you mean one of the calendars from cloud.entropia.de but I can't find any public link or reference to their iCal feeds. Is there a broad agreement to use data from the Entropia nextcloud instance where only registered and unlocked members can see the events and to make it publicly available?

**Comment by stirlingzero** [comment]
You can find those at the Wiki of Entropia: https://entropia.de/Ical

**Comment by stirlingzero** [comment]
I would suggest to use the "Entropia", "Entropia-Events" and "Freifunk"- Calender's

**Comment by pascalwittler** [comment]
Oh ok nice, I just didn't find the iCal wiki article because I thought the feeds surely would be linked above the events list.

**Comment by stirlingzero** [comment]
Es existiert jetzt auch ein Public-Kalender für die Webseite in dem ausgewählte Dinge

**Comment by stirlingzero** [comment]
^Wo die Fettfinger überall hin rutschen ...

**Comment by pascalwittler** [comment]
https://github.com/entropia/landing-page/pull/54

https://github.com/entropia/landing-page/pull/55

**Comment by pascalwittler** [comment]
"Project iCal" has been cancelled by @stirlingzero again
