### ISSUE TITLE
Terminlinks sollten auch auf der Landing Page Links bleiben

### ISSUE THREAD

**Issue by jdreichmann** [entropia/landing-page#19]
Vergleiche

![image](https://user-images.githubusercontent.com/34141868/218316396-39437e8d-6d38-45e0-bf25-8e99695ca049.png)

zu

![image](https://user-images.githubusercontent.com/34141868/218316422-70c87a1d-52ef-415e-8f9d-634cecde2255.png)

"Jitsi Meet" ist nicht besonders aussagekraeftig

**Comment by promasu** [comment]
![image](https://user-images.githubusercontent.com/23510137/218316825-43497c5f-51f3-4dd7-b3c5-bf1fa4659d77.png)

Es sieht bei mir allgemein kaputt aus

**Comment by evlli** [comment]
https://github.com/entropia/landing-page/blob/80fb8325f5f526f6736fc8421e3d532c39f702f5/public/api/entropia-wiki-events-json-api.php#L40-L44

sieht mir nach einem off-by one error aus, die schöne lösung wäre https://github.com/entropia/landing-page/issues/17 zu implementierten, dafür sollten wir aber ggf. kalender für public service announcements wie stromschwankungen von terminen trennen, damit es bei neulingen nicht zu verwirrungen kommt.

**Comment by soc** [comment]
Ich vermute, dass sich da etwas zwischen den PHP-Versionen geändert hat, unter entropia.dev sah es vorher ja richtig aus.

**Comment by promasu** [comment]
@evlli Off-by-one was fixed by #24

**Comment by pascalwittler** [comment]
Jetzt sind hier zwei Issues durcheinandergekommen: Die verrutschten Spalten sind ja bereits gelöst, bleibt die Frage nach den Links. Es gibt Issue #17 zur Neuimplementierung der Terminliste mit einem oder beiden der existitierenden Kalendern aus cloud.derpunkt.de – ich würde aber schätzen, dass es schneller geht, die Tabelle aus dem Wiki mit Links zu übernehmen, als einen neuen Kalender anzubinden.

Deshalb schlage ich vor, die Links aus der Wiki-Tabelle zu übernehmen und die Diskussion zu #17 hinten anzustellen bzw. dort noch etwas laufen zu lassen.
