### ISSUE TITLE
Neue Implementation des Impressums

### ISSUE THREAD

**Issue by stirlingzero** [entropia/landing-page#25]
Man könnte das ja mal aus dem Wiki auf die Webseite ziehen und schön machen

**Comment by pascalwittler** [comment]
Also ich finde ja viele Inhalte sind es wert, schön gemacht zu werden, aber ob wir uns als zweites direkt trauen sollten, mit einer jungen, frechen, lauten visuellen Konzeption für DAS Aushängeschild des Vereins (Impressum) den restlichen CCC in den Schatten zu stellen? :stuck_out_tongue:

**Comment by pascalwittler** [comment]
Und noch eine ernst gemeinte Anmerkung: Wie locker-flockig wäre denn die nginx-Konfiguration für Unterseiten (entropia.de/impressum etc.) und ggf. eine Sperre im Wiki für Artikel-Titel, die zur gleichen URL führen würden, überhaupt umzusetzen – und wie würde man eine Liste der nicht im Wiki erstellbaren Subseiten für alle nachvollziehbar handhaben?

**Comment by pascalwittler** [comment]
Keine Rückmeldung und keine Klärung der technischen Machbarkeit seit 1,5 Jahren
