### ISSUE TITLE
Neue Implementation der Datenschutz-Seite

### ISSUE THREAD

**Issue by stirlingzero** [entropia/landing-page#26]
Gerade da wir Subseiten haben, deren Content zum Teil nicht durch uns verwaltet wird, könnten wir die Datenschutz-Erklärung anpassen und aus dem Wiki auf die Webseite ziehen.

**Comment by pascalwittler** [comment]
> Gerade da wir Subseiten haben, deren Content zum Teil nicht durch uns verwaltet wird (...)

Was ist damit genau gemeint? @stirlingzero

**Comment by pascalwittler** [comment]
siehe auch https://github.com/entropia/landing-page/issues/25#issuecomment-1439194068

**Comment by pascalwittler** [comment]
Keine Rückmeldung und keine Klärung der technischen Machbarkeit seit 1,5 Jahren
