### ISSUE TITLE
Hackerfrühstück

### ISSUE THREAD

**Issue by soc** [entropia/landing-page#35]
> Wir hacken und frühstücken

Sollte vllt. richtigerweise

> Wir räumen auf und frühstücken

heißen, oder?

**Comment by pascalwittler** [comment]
Kompromissvorschlag: "Wir räumen auf, hacken und frühstücken."

**Comment by soc** [comment]
Passt!

**Comment by stirlingzero** [comment]
Hackerfrystyck sowie aufräumen wurde vor längerem hinzugefügt
