### ISSUE TITLE
Landing Page für unseren Space anpassen

### ISSUE THREAD

**Issue by inktrap** [entropia/landing-page#47]
Hello,

dank MIT-License ist das ja eigentlich kein Thema, ich dachte mir ich frage dennoch vorher mal. Wir haben auf chaosdorf.de noch ein Wordpress und eure Seite ist einfach so viel schicker, schöner, simpler usw. <3

Ihr habt ja auch vor eine englische Version anzubieten. Ich bin schon ein Freund von KISS aber wollte zumindest mal fragen ob es sinnvoll wäre das per jinja2 (oder einer vergleichbaren/ähnlichen template-Engine) zu realisieren? Muss ja nicht immer direkt hugo & co sein. Aber ich würde es doch eher bei HTML belassen da sich da ja auch nicht so viel ändern dürfte bzw ist es halt wirklich einfach.

**Comment by pascalwittler** [comment]
Hey ✌🏼 Vielen Dank für das Lob!

Zwei Unklarheiten zu deinem Issue:

1. Fragst du, ob wir die landing page in einer templating engine umsetzen möchten oder ob wir das anderen empfehlen bzw. nicht empfehlen?

2. Worauf bezieht sich dein letzter Satz "Aber ich würde es doch eher bei HTML belassen […]"?

Eine Umsetzung der landing page in einer nicht-statischen Form ist nach meiner Kenntnis bei Entropia nicht geplant.

Es deutet sich eher ab, dass wir mit einem neuen Theme für unser MediaWiki die statische landing page wieder ersetzen könnten. Das ist aber noch nicht entschieden.

Generell dürfte sich der Aufwand in Grenzen halten, die relativ generischen HTML- und CSS-Bestandteile in eine templating engine deiner Wahl zu kopieren.

Es dürfte nichts dagegen sprechen, dich zu bedienen und nach Belieben Anpassungen vorzunehmen 😊

**Comment by inktrap** [comment]
Ich wollte lediglich diesen Gedanken dass man das  per Templating-Engine erstellen könnte mal in den Raum werfen.

Also würde ich zu 1. sagen sowohl als auch ;P aber das ist ja nun sowieso schon beantwortet.

2. Bezieht sich darauf dass ich das HTML-file als wunderschön einfach empfinde und ich persönlich aus KISS-Gründen eher von einer Templating-Engine absehen würde.

Was wären die Vorteile das im Rahmen von Mediawiki einzubinden? Geht es darum, dass möglichst viele Menschen das updaten und pflegen können sollen?

Nachdem ich das ein wenig besprochen habe zeichnet sich ab, dass auch noch nicht entschieden ist, was wir machen, aber grünes Licht bzgl Anpassungen ist schon mal super.

**Comment by pascalwittler** [comment]
Es geht nicht darum, die landing page technisch ins Wiki zu integrieren, sondern ein aktuell in Vorbereitung befindliches, neues Theme für unser ohnehin bestehendes MediaWiki auszurollen und dadurch ggf. ohne die eigenständige, statische landing page auszukommen.

Da hier noch nichts final entschieden ist, möchte ich die Diskussion weder auf Github parallel fortführen, noch Argumente auswählen und dann nur diese in die Öffentlichkeit stellen.

Dein erster Gedanke zur niedrigschwelligen Editierbarkeit ist aber sicher sehr naheliegend.

**Comment by soc** [comment]
@inktrap Es gibt genug Dinge (fehlender Content auf Englisch, fehlende englischsprachinge Linkziele usw.), die man in der deutschen und englischen Variante eh getrennt lösen müsste.

Deswegen war da mein Ansatz, dass wir keine zusätzlichen Werkzeuge einführen für etwas, was erst mal nur eine zusätzliche HTML-Seite wäre.

Wenn wir irgendwann zu Englisch und Deutsch auch noch Französisch, Italienisch, Indisch und Chinesisch haben wollen würden, müsste man das sicherlich neu evaluieren.

**Comment by inktrap** [comment]
@soc Das mit der Wiki-Reintegration war ein Missverständnis,  siehe den Beitrag von Pascal.

Ich würde die Issue jetzt schließen, da meine eigentliche Frage ja geklärt ist. Danke euch :)

**Comment by soc** [comment]
@inktrap Gerne!
