### ISSUE TITLE
Navigation hat auf kleinen Bildschirmen zu wenig Platz

### ISSUE THREAD

**Issue by pascalwittler** [entropia/landing-page#64]
Seit Commit bdb77da hat die Hauptnavigation einen neuen Link „Code of Conduct“, dessen Platzbedarf auf kleinen Bildschirmen zu einem optisch unschönen Ergebnis führt:

![Screen Shot 2024-12-07 at 13 39 02](https://github.com/user-attachments/assets/a9eb04f7-4467-4e91-94fc-9f046038fb69)

![Screen Shot 2024-12-07 at 13 39 36](https://github.com/user-attachments/assets/b4cb5d43-5798-4dab-8c6b-bbf3fb4ba448)

**Comment by soc** [comment]
@pascalwittler Zu "CoC" kürzen wäre wohl die Lösung mit dem geringsten Aufwand.

**Comment by pascalwittler** [comment]
@soc Habe nichts dagegen

**Comment by pascalwittler** [comment]
Also wann geht's los? Der Frontend-Bug ist ja jetzt online …

**Comment by soc** [comment]
> Also wann geht's los? Der Frontend-Bug ist ja jetzt online …

Äh shit, stimmt ... ich versuchs morgen vllt. :sweat:

**Comment by pascalwittler** [comment]
Adressiert in fbc44a7 von @soc
