### ISSUE TITLE
Automatisches oder manuelles Deployment

### ISSUE THREAD

**Issue by pascalwittler** [entropia/landing-page#65]
Seitdem die landing page online gestellt wurde, ist jede Aktualisierung auf dem Webserver ein manueller Prozess mit wechselnden, wenigen zuständigen Personen schwankender Erreichbarkeit.

Mehrere Male wurden gerüchteweise Vorhaben genannt, die ein automatisches Deployment aus diesem Repository auf den Webserver in Aussicht stellten.

Dieses Issue soll nach rund einem Jahr seit der letzten ergebnislosen, mündlichen Diskussion noch einmal nachfragen und den (zumindest von mir) nach wie vor bestehenden Wunsch nach einem automatischen Deployment oder einem deutlich verlässlicheren, schnelleren manuellen Prozess noch einmal bekräftigen.

**Comment by pascalwittler** [comment]
**Vorschlag 1: `git pull` / `git fetch` als cronjob auf dem Webserver**

Der `master`-Branch dieses Repositories könnte mit `git` regelmäßig, z.B. alle paar Minuten per Cronjob auf den Webserver synchronisiert werden.

Durch bereits existierende Einstellungen der Zugriffsrechte, Review- und Merge-Prozesse existiert hier eine Qualitätssicherung. Höhere Ansprüche oder Gegenargumente gerne als Kommentar unter diesem Kommentar.

**Comment by stirlingzero** [comment]
Find ich gut. Leider habe ich keinen Zugriff mehr auf den Host und kann daher keinen Cronjob einrichten : /

**Comment by pascalwittler** [comment]
@stirlingzero Dann gerne deinen Namen aus der Spalte „Wer hat Zugriff?“ im Wiki entfernen :wink:

**Comment by stirlingzero** [comment]
Oh, Danke für die Erinnerung. Daran hatte ich gar nicht mehr gedacht : )

**Comment by pascalwittler** [comment]
**Vorschlag 2: Menschen, die sich um die landing page kümmern, `git push` auf den Webserver ermöglichen**

Als Alternative oder Ergänzung zu [Vorschlag 1](#issuecomment-2525113360) könnte der Webserver in welcher Form auch immer so weit zugänglich gemacht werden, dass er als zusätzliches `git remote` neben Github für eine Gruppe von Menschen, die sich aktiv um die landing page kümmern, zur Verfügung stünde.

So könnte diese Gruppe per `git push` selbständig und ohne zeitlichen Verzug einen bestimmten Stand auf den Webserver synchronisieren.

**Comment by jens1o** [comment]
Danke für das Aufbringen des Themas! Fände es sehr gut, wenn wir da mal zu einer Lösung kommen, und für mich sind wir gerade auf einem guten Weg dahin.

Ich bin für Vorschlag 2. Solange wir keine wirkliche Übersicht in die Systeme (z.B. bei einem automatisierten Deployment via  GitHub Actions und der damit verbundenen Einsicht über die Logs) haben, sollte das deployen imho bewusst passieren. Vorschlag 1 wäre mir zu "ja ist mir doch egal ob es jetzt tut oder nicht". :D

**Comment by pascalwittler** [comment]
Falls jemand weiß, wer gerade wirklich Zugriff auf den Webserver und/oder Einfluss auf den Prozess hat, entsprechenden Personen gerne dieses Issue zuweisen.

**Comment by pascalwittler** [comment]
> Ich habe auch keinen Zugriff auf den Webserver.

Dann gerne deine Eintragung in der oops-Liste prüfen und z.B. ergänzen, wofür du Ansprechperson bist 🙂

**Comment by promasu** [comment]
Wir können sehr gerne erstmal ein git fetch + git pull aufm Webserver im Cron hinterlegen. Eventuell sollte man vorher prüfen/festlegen, wer alles auf den main-Branch hier pushen darf. Ich kann mir das gerne später mal anschauen und einrichten

**Comment by soc** [comment]
@promasu Prinzipiell haben alle Entropianer `write`-Rechte, allerdings is der main branch protected und benötigt ein Approval. (Wer genau approven kann, keine Ahnung.)

Wir können gerne nachschauen, ob die Berechtigungen passen, allerdings nicht als Blocker zum Deployment-Thema.

**Comment by promasu** [comment]
Main Branch protected reicht mir vollkommen aus.

Fände es nur nicht gut, wenn wir automatisch von GitHub pullen, aber die halbe Welt nach main schreiben darf und damit potenziell irgendwelcher Schwachsinn auf die Seite kommt ;)

**Comment by margau** [comment]
Ich kann bei der Verwaltung des Deployments im Status quo leider nicht weiterhelfen (mangels Access auf die Webserver und Kenntnis der Architektur).
Falls wir jedoch ein Deployment mit S3 (Garage etc.) und github actions bauen wollen würden, kann ich mich da gerne mit drum kümmern.

**Comment by promasu** [comment]
Crontab ist eingerichtet. Deployment ist alle 10 Minuten
