### ISSUE TITLE
PHP-Version auf dem Webserver

### ISSUE THREAD

**Issue by pascalwittler** [entropia/landing-page#66]
* Welche PHP-Version läuft aktuell auf dem Webserver?
* Nach welchen Kriterien wird die PHP-Version ggf. geändert / aktualisiert?
* Wie kann die Gruppe hinter der landing page ggf. davon erfahren, um Kompatibilität zu gewährleisten?

**Comment by pascalwittler** [comment]
MediaWiki behauptet, unter PHP 8.0 zu laufen. Ist das die selbe Umgebung, in der die landing page läuft?

**Comment by promasu** [comment]
Wiki und landing page sind auf der gleichen VM. Es muss natürlich immer geschaut werden, dass auf dem Server eine Version genutzt wird, die mit dem Wiki kompatibel ist, damit uns das nicht um die Ohren fliegt.

Ich würde sagen, dass du dich bestenfalls erstmal an die PHP Version vom Wiki hältst.

Eine Parallelinstallation mit mehreren Versionen sollte aber prinzipiell möglich sein, solange die PHP-Version in Paketquellen zur Verfügung steht.

**Comment by pascalwittler** [comment]
Es gab nur ganz am Anfang und einmal zwischendurch Unklarheiten und Menschen hatten dann auf Verdacht Code rückwärtskompatibel gemacht.

Wenn wir auf der Wiki-Spezialseite jederzeit die aktuelle Version finden, können wir uns danach richten.

Ich werde einen Reminder basteln, der die Versionsnummer dort prüft, damit wir ggf. reagieren können.
